# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf1b2e622825e8284cfd6de1ad9cc06ee1b527504a8ce64d0bf1634a3d32e3f0b6a4c10bbd1763be3b00e26a0c0ac62f89e1e0f26505f0437a348e88d3c63067

test:
  secret_key_base: 49e3893afd7857da0e934f214aa7cac9f05522957241427aedc0b57af5ee529f80b05589c93230f1bea7fc8ee8db19b755b2ed3ba79888e62f09f498e4892164

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
